language: php

sudo: required
dist: trusty
group: edge

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - hhvm
    - hhvm-nightly

allow_failures:
    - hhvm
    - hhvm-nightly

before_script:
    - if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then composer install; else composer install --ignore-platform-reqs; fi

script: phpunit
