language: php

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

matrix:
    include:
        - php: hhvm-stable
          sudo: required
          dist: trusty
        - php: 7.0
        - php: 7.1
    allow_failures:
        - php: hhvm-stable
    fast_finish: true

allow_failures:
    - hhvm
    - hhvm-nightly

before_install:
    - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
    - composer install

install:
    - travis_retry composer install
